import { GitHubClient } from "./github";
import { pickRelevantFiles, planEdit } from "./claude";
import { postMessage } from "./slack";
import type { Bindings } from "./env";

export interface FlowArgs {
	env: Bindings;
	request: string;
	channelId: string;
	threadTs: string;
	userName: string;
	userId: string;
}

export async function runEditFlow(args: FlowArgs): Promise<void> {
	const { env, request, channelId, threadTs, userName, userId } = args;
	const gh = new GitHubClient(env.GITHUB_TOKEN, env.GITHUB_OWNER, env.GITHUB_REPO);
	const post = (text: string) =>
		postMessage(env.SLACK_BOT_TOKEN, channelId, text, threadTs);

	try {
		await post("🔍 Reading the repo…");
		const branch = await gh.getDefaultBranch();
		const tree = await gh.listTextFiles(branch.sha);

		await post(`🧠 Asking Claude which files matter (${tree.length} in tree)…`);
		const candidatePaths = await pickRelevantFiles(
			env.ANTHROPIC_API_KEY,
			request,
			tree.map((f) => f.path),
		);
		if (candidatePaths.length === 0) {
			throw new Error("Claude couldn't find a relevant file");
		}

		const candidates = await Promise.all(
			candidatePaths.map((p) => gh.getFileContent(p, branch.name)),
		);

		await post(`✏️ Generating change for: \`${candidatePaths.join("`, `")}\``);
		const plan = await planEdit(
			env.ANTHROPIC_API_KEY,
			request,
			tree.map((f) => f.path),
			candidates.map((c) => ({ path: c.path, content: c.content })),
		);

		const target = candidates.find((c) => c.path === plan.file)!;

		const branchName = `sparkles/${slugify(plan.summary)}-${shortId()}`;
		await gh.createBranch(branchName, branch.sha);
		await gh.commitFile({
			branch: branchName,
			path: plan.file,
			content: plan.newContent,
			sha: target.sha,
			message: plan.summary,
		});

		const pr = await gh.openPR({
			branch: branchName,
			base: branch.name,
			title: plan.summary,
			body: [
				`Requested by <@${userId}> (${userName}) via Slack:`,
				"",
				`> ${request}`,
				"",
				"---",
				"_Generated by [sparkles-slack](https://github.com)_ — review carefully before merging.",
			].join("\n"),
		});

		await post(`✅ PR #${pr.number} opened: ${pr.url}`);
	} catch (err) {
		const message = err instanceof Error ? err.message : String(err);
		await post(`❌ Failed: ${message}`);
		throw err;
	}
}

function slugify(s: string): string {
	return s
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, "-")
		.replace(/^-|-$/g, "")
		.slice(0, 40);
}

function shortId(): string {
	return Math.random().toString(36).slice(2, 8);
}
